### ISSUE TITLE
Deserialization issue

### ISSUE THREAD

**Issue by Intagrit-F** [moh-hassan/odata2poco#16]
poco generated for Northwind V2 service:
dotnet -o2pgen -l -r http://services.odata.org/V2/Northwind/Northwind.svc -n

The o2pgen does not support the d/results/metadata structure of the odata response?

e.g.
{
    "d": {
        "results": [
            {
                "__metadata": {
                    "uri": "https://services.odata.org/V2/Northwind/Northwind.svc/Shippers(1)",
                    "type": "NorthwindModel.Shipper"
                },
                "ShipperID": 1,
                "CompanyName": "Speedy Express",
                "Phone": "(503) 555-9831",
                "Orders": {
                    "__deferred": {
                        "uri": "https://services.odata.org/V2/Northwind/Northwind.svc/Shippers(1)/Orders"
                    }
                }
            },
            {

**client code:**
_httpClient.BaseAddress = new Uri("http://services.odata.org");
_httpClient.Timeout = new TimeSpan(0, 0, 30);
_httpClient.DefaultRequestHeaders.Clear();
_httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
var response = await _httpClient.GetAsync("/V2/Northwind/Northwind.svc/Shippers");
response.EnsureSuccessStatusCode();
var content = await response.Content.ReadAsStringAsync();
var shipperList = new List<Shipper>();
shipperList = JsonConvert.DeserializeObject<List<Shipper>>(content);

**Comment by moh-hassan** [comment]
Welcome to OData2Poco project.
o2pgen generate POCO classes from OData feeds v1..v4 that can fit with OData client tools. 
These tools manage deserialization using POCO classes for Odata v1..v4 due to the variations of json schema plus other OData operations like Expand,Navigate,...

Deserialization is out of the scope of the project and is left to the OData client tools.

If you are using HttpClient, you have to extract the rootElement of json data and deserialize it (that what is done by OData client tools);
For example, use the following code to extract the root `d/results` and deserialize the content:

		 JObject jobject = JObject.Parse(content);
		 var rootElement= jobject["d"]["results"].ToString();
		 var shipperList = JsonConvert.DeserializeObject<List<Shipper>>(rootElement);
		 
Let me know if that is help to resolve your issue.

**Comment by Intagrit-F** [comment]
@moh-hassan Thanks for the explanation and suggestion. Using Simple.Odata.Client solves my issue.
