### ISSUE TITLE
Generator doesn't respect Enum indexes

### ISSUE THREAD

**Issue by andresdsep** [moh-hassan/odata2poco#7]
An enum on our API side reads like so:
``` c#
public enum FeeVariant
{
    Normal = 1,
    StdAbs = 2,
    AddAbs = 3,
    Holiday = 4,
    // others here...
}
```

The generated enum by odata2poco is:
``` C#
public enum FeeVariant { Normal, StdAbs, AddAbs, Holiday, /* others here... */ }
```

As a result, the index of the generated enum values is wrong.

**Comment by moh-hassan** [comment]
Welcome to Odata2Poco Project.
The issue is planned to be resolved.

**Comment by andresdsep** [comment]
I don't know whether to add it as a new bug or related to this, but the `FlagAttribute` is also missing from the enum

**Comment by moh-hassan** [comment]
>I don't know whether to add it as a new bug 

The elements of enum has by default an integer value  starting from 0 and it's incremented by 1  in the same order of occurrence,  so

		public enum FeeVariant { Normal, StdAbs, AddAbs, Holiday, /* others here... */ }

will be

		Normal= 0
		StdAbs= 1
		AddAbs= 2
		Holiday= 3

So it keep its correct  index order.

Modifying it to set the values as given in the Metadata of OData is enhancement will  be added in the next release.

>the FlagAttribute is also missing from the enum

The enum needn't to have FlagAttribute 

The FlagAttribute should be used whenever the enumerable represents a collection of flags (for bitwise operation), rather than a single value. 

In that case, values of enum elements should be 1,2, 4,8 . 16 (powers of two) to do bit operation, otherwise you get a [warning: CA2217: Do not mark enums with FlagsAttribute](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2217-do-not-mark-enums-with-flagsattribute?view=vs-2017)



We can [mark the enum with the FlagsAattribute](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1027-mark-enums-with-flagsattribute?view=vs-2017. ) if the values of enum in the Metadata are powers of two

**Comment by andresdsep** [comment]
I meant another one of our enums which has the `FlagAttribute` is missing both the power of 2 indexes and the attribute

**Comment by moh-hassan** [comment]
Can you check if the metadata of your OData service contain FlagAttribute? can you show me that xml enum part (and its annotation), so i can parse it. ?

**Comment by andresdsep** [comment]
``` xml
<EnumType Name="PrintRunOptions" IsFlags="true">
    <Member Name="PrintPaymentReceipts" Value="1"/>
    <Member Name="PrintRegisteredCarerReceipts" Value="2"/>
    <Member Name="PrintAccountSlips" Value="16"/>
</EnumType>
```

**Comment by moh-hassan** [comment]
Thanks Andres Sepulveda,
The xml fragement help, and FlagAttribute with Enum values will be available in the next release, like:

                [Flags]
		public enum FeeVariant
		{
			Normal = 1,
			StdAbs = 2,
			AddAbs = 3,
			Holiday = 4,
			// others here...
		}

**Comment by moh-hassan** [comment]
Hi Andres Sepulveda,
You can try the new Pre-release 3.0.0-RC1.240
Download [o2pgen ](https://github.com/moh-hassan/odata2poco/releases/download/3.0.0.240/o2pgen.exe)from  [github release page](https://github.com/moh-hassan/odata2poco/releases)

This pre release resolves your issue#7 and add extra attributes: 
proto  to support protobuf 
dm   for datamember/datacontract
display  for display attribute
db for key/required and table attributes 
I greatly appreciate your feedback.

**Comment by andresdsep** [comment]
I am now seeing correct indexing and `Flags` attribute where needed. Thank you

**Comment by moh-hassan** [comment]
Thanks @andresdsep  for feedback.
I'm Glad  you get correct indexing and Flags.

**Comment by moh-hassan** [comment]
Hi @andresdsep 
.Net Core Global tool is [available](https://github.com/moh-hassan/odata2poco/releases/tag/3.0.0.262)
I appreciate your feedback

**Comment by moh-hassan** [comment]
OData2Poco.dotnet.o2pgen v3.0.3 have been published to [nuget](https://www.nuget.org/packages/OData2Poco.dotnet.o2pgen/3.0.3)

**Comment by moh-hassan** [comment]
OData2Poco.CommandLine (Console tool o2pgen ) v3.0.3 is published to [nuget ](https://www.nuget.org/packages/OData2Poco.CommandLine/)
